name: create file

on:
  schedule:
 #    Runs at 2am UTC
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}      
      - uses: 1arp/create-a-file-action@0.4.5
        with:
          path: '/simpleRHistogram'
          isAbsolutePath: true
          file: 'test.txt'
          content: |
            Hello
            World
