name: Update

on:
  schedule:
 #    Runs at 2am UTC
    - cron: "*/10 * * * *"
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Create file
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: python ./.github/workflows/todo_List.py
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
